UPDATE layers_attribute SET attribute_label = 'Grado de marginación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'gmu2010') AND attribute='GMU2010';
UPDATE layers_attribute SET attribute_label = 'Grado promedio de escolaridad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2010') AND attribute='GRAPROES';
UPDATE layers_attribute SET attribute_label = 'Población total (habitantes)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2011') AND attribute='POBTOT';
UPDATE layers_attribute SET attribute_label = 'Número de personas con alguna discapacidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2012') AND attribute='PCON_LIM';
UPDATE layers_attribute SET attribute_label = 'Número de personas que habla alguna lengua indígena' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2013') AND attribute='PY3M_HLI';
UPDATE layers_attribute SET attribute_label = 'Número de personas con acceso a servicios de salud' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2014') AND attribute='PDER_SS';
UPDATE layers_attribute SET attribute_label = 'Densidad poblacional (hab/ha)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2015') AND attribute='POBTOT_HA';
UPDATE layers_attribute SET attribute_label = 'PEA' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2016') AND attribute='PEA';
UPDATE layers_attribute SET attribute_label = 'Grado de dependencia económica' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2017') AND attribute='RZN_DEP_EC';
UPDATE layers_attribute SET attribute_label = 'Grado de dependencia económica' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2018') AND attribute='RZN_DEP__1';
UPDATE layers_attribute SET attribute_label = 'Clave escolar' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'usaer') AND attribute='CVE_ESC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'usaer') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Número' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'usaer') AND attribute='NUM';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'usaer') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'usaer') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Clave escolar' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cam') AND attribute='CVE_ESC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cam') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cam') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cam') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Aulas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cam') AND attribute='AULA_EXIST';
UPDATE layers_attribute SET attribute_label = 'Clave escolar' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'preescolar') AND attribute='CVE_ESC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'preescolar') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'preescolar') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'preescolar') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'preescolar') AND attribute='SOST';
UPDATE layers_attribute SET attribute_label = 'Aulas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'preescolar') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Clave escolar' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'primaria') AND attribute='CVE_ESC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'primaria') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'primaria') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'primaria') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'primaria') AND attribute='SOST';
UPDATE layers_attribute SET attribute_label = 'Aulas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'primaria') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Clave escolar' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'secundaria') AND attribute='CVE_ESC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'secundaria') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'secundaria') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'secundaria') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'secundaria') AND attribute='SOST';
UPDATE layers_attribute SET attribute_label = 'Aulas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'secundaria') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Clave escolar' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cap_trab') AND attribute='CVE_ESC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cap_trab') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cap_trab') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cap_trab') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Aulas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cap_trab') AND attribute='AULA';
UPDATE layers_attribute SET attribute_label = 'Talleres' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cap_trab') AND attribute='TALLER';
UPDATE layers_attribute SET attribute_label = 'Clave escolar' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_abierto') AND attribute='CVE_ESC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_abierto') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Modalidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_abierto') AND attribute='MODAL';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_abierto') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_abierto') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_abierto') AND attribute='SOST';
UPDATE layers_attribute SET attribute_label = 'Aulas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_abierto') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Clave escolar' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_gral_tec') AND attribute='CVE_ESC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_gral_tec') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Modalidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_gral_tec') AND attribute='MODAL';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_gral_tec') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_gral_tec') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_gral_tec') AND attribute='SOST';
UPDATE layers_attribute SET attribute_label = 'Aulas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_gral_tec') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Clave de la institución' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'universidad') AND attribute='CVE_INST';
UPDATE layers_attribute SET attribute_label = 'Institución' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'universidad') AND attribute='INST';
UPDATE layers_attribute SET attribute_label = 'Clave escolar' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'universidad') AND attribute='CVE_ESC';
UPDATE layers_attribute SET attribute_label = 'Nombre de la escuela' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'universidad') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'universidad') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'universidad') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'universidad') AND attribute='SOST';
UPDATE layers_attribute SET attribute_label = 'Aulas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'universidad') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cultura') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cultura') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cultura') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cultura') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Unidad básica de servicio (UBS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cultura') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo de UBS' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cultura') AND attribute='DESC_UBS';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'salud') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'salud') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'salud') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'salud') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Unidad básica de servicio (UBS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'salud') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo de UBS' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'salud') AND attribute='DESC_UBS';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'asist_social') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'asist_social') AND attribute='INST';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'asist_social') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'asist_social') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'asist_social') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Unidad básica de servicio (UBS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'asist_social') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo de UBS' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'asist_social') AND attribute='DESC_UBS';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'farmacia') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'farmacia') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'farmacia') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'farmacia') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'farmacia') AND attribute='INST';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tda_ctro_com') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tda_ctro_com') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tda_ctro_com') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tda_ctro_com') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tda_ctro_com') AND attribute='INST';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tianguis') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tianguis') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tianguis') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tianguis') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tianguis') AND attribute='INST';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'abarrote_tda_autoserv') AND attribute='nom_estab';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'merc_sobreruedas') AND attribute='COLONIA';
UPDATE layers_attribute SET attribute_label = 'Ubicación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'merc_sobreruedas') AND attribute='UBICACION';
UPDATE layers_attribute SET attribute_label = 'Oferentes' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'merc_sobreruedas') AND attribute='OFERENTES';
UPDATE layers_attribute SET attribute_label = 'Agrupación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'merc_sobreruedas') AND attribute='AGRUPACION';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'abasto') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'abasto') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'abasto') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'abasto') AND attribute='COL';
UPDATE layers_attribute SET attribute_label = 'Sostenimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'abasto') AND attribute='INST';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'comunicacion') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'comunicacion') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'comunicacion') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'comunicacion') AND attribute='COLONIA';
UPDATE layers_attribute SET attribute_label = 'Unidad básica de servicio (UBS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'comunicacion') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo de UBS' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'comunicacion') AND attribute='DESC_UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'transporte') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'transporte') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'transporte') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'transporte') AND attribute='COLONIA';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'rec_espect') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'rec_espect') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'rec_espect') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'rec_espect') AND attribute='COLONIA';
UPDATE layers_attribute SET attribute_label = 'Unidad básica de servicio (UBS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'rec_espect') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo de UBS' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'rec_espect') AND attribute='DESC_UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_verde') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_verde') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_verde') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_verde') AND attribute='COLONIA';
UPDATE layers_attribute SET attribute_label = 'Unidad básica de servicio (UBS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_verde') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo de UBS' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_verde') AND attribute='DESC_UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'deporte') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'deporte') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'deporte') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'deporte') AND attribute='COLONIA';
UPDATE layers_attribute SET attribute_label = 'Unidad básica de servicio (UBS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'deporte') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo de UBS' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'deporte') AND attribute='DESC_UBS';
UPDATE layers_attribute SET attribute_label = 'Razón Social' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'admon_pub') AND attribute='raz_social';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'admon_pub') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'admon_pub') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'admon_pub') AND attribute='COLONIA';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'admon_pub') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'serv_urb') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'serv_urb') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'serv_urb') AND attribute='COLONIA';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'serv_urb') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Unidad básica de servicio (UBS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'serv_urb') AND attribute='UBS';
UPDATE layers_attribute SET attribute_label = 'Tipo de UBS' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'serv_urb') AND attribute='DESCRIP_UB';
UPDATE layers_attribute SET attribute_label = 'Estado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'hidrantes') AND attribute='ESTADO';
UPDATE layers_attribute SET attribute_label = 'Número de planta' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'planta_pot') AND attribute='PLANTA_POT';
UPDATE layers_attribute SET attribute_label = 'Capacidad (LPS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'planta_pot') AND attribute='CAP_LS';
UPDATE layers_attribute SET attribute_label = 'Número de zona' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'zonas_cespm') AND attribute='ID';
UPDATE layers_attribute SET attribute_label = 'Material' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_ap') AND attribute='MATERIAL';
UPDATE layers_attribute SET attribute_label = 'Año de construcción' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_ap') AND attribute='CONSTRUCCI';
UPDATE layers_attribute SET attribute_label = 'Vida útil' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_ap') AND attribute='VIDAUTIL';
UPDATE layers_attribute SET attribute_label = 'Diámetro' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_ap') AND attribute='DIAM_INCH';
UPDATE layers_attribute SET attribute_label = 'Longitud (m)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_ap') AND attribute='LONGITUD';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cob_potable') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Planta' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ptar_cespm') AND attribute='PLANTA';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ptar_cespm') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Laguna aireada' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ptar_cespm') AND attribute='LAG_AIRADA';
UPDATE layers_attribute SET attribute_label = 'Laguna de sedimentación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ptar_cespm') AND attribute='LAG_SEDIM';
UPDATE layers_attribute SET attribute_label = 'Laguna facultativa' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ptar_cespm') AND attribute='LAG_FACULT';
UPDATE layers_attribute SET attribute_label = 'Laguna de maduración' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ptar_cespm') AND attribute='LAG_MAD';
UPDATE layers_attribute SET attribute_label = 'Capacidad (LPS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ptar_cespm') AND attribute='CAP_LPS';
UPDATE layers_attribute SET attribute_label = 'Planta' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ptar_lodos_act') AND attribute='UBICACION';
UPDATE layers_attribute SET attribute_label = 'Capacidad (LPS)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ptar_lodos_act') AND attribute='CAP_LPS';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sist_bomb') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sist_bomb') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sist_bomb') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Equipos' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sist_bomb') AND attribute='EQUIPOS';
UPDATE layers_attribute SET attribute_label = 'Tipo de bombas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sist_bomb') AND attribute='BOMBAS';
UPDATE layers_attribute SET attribute_label = 'Capacidad (HP)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sist_bomb') AND attribute='CAP_HP';
UPDATE layers_attribute SET attribute_label = 'Generador eléctrico' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sist_bomb') AND attribute='GEN_ELECT';
UPDATE layers_attribute SET attribute_label = 'Material' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_as') AND attribute='MATERIAL';
UPDATE layers_attribute SET attribute_label = 'Año de construcción' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_as') AND attribute='CONSTRUCCI';
UPDATE layers_attribute SET attribute_label = 'Vida útil' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_as') AND attribute='VIDAUTIL';
UPDATE layers_attribute SET attribute_label = 'Diámetro' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_as') AND attribute='DIAMETRO';
UPDATE layers_attribute SET attribute_label = 'Conducción' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_as') AND attribute='CONDUCCION';
UPDATE layers_attribute SET attribute_label = 'Longitud (m)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_as') AND attribute='LONGITUD';
UPDATE layers_attribute SET attribute_label = 'Años de vida' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_as') AND attribute='ANO_VIDA';
UPDATE layers_attribute SET attribute_label = 'Vida restante (años)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_as') AND attribute='REST_VIDA';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cob_sanitario') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'carc_pluvial') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'carc_pluvial') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Equipos' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'carc_pluvial') AND attribute='EQUIPOS';
UPDATE layers_attribute SET attribute_label = 'Tipo de bombas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'carc_pluvial') AND attribute='BOMBAS';
UPDATE layers_attribute SET attribute_label = 'Capacidad (HP)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'carc_pluvial') AND attribute='CAP_HP';
UPDATE layers_attribute SET attribute_label = 'Generador eléctrico' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'carc_pluvial') AND attribute='GEN_ELECT';
UPDATE layers_attribute SET attribute_label = 'Material' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_pluvial') AND attribute='MATERIAL';
UPDATE layers_attribute SET attribute_label = 'Diámetro' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_pluvial') AND attribute='DIAMETRO';
UPDATE layers_attribute SET attribute_label = 'Año de construcción' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_pluvial') AND attribute='CONSTRUCCI';
UPDATE layers_attribute SET attribute_label = 'Años de vida' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_pluvial') AND attribute='VIDAUTIL';
UPDATE layers_attribute SET attribute_label = 'Longitud (m)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_ppal_pluvial') AND attribute='LONGITUD';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dren_cubierto') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dren_abierto') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dren_abierto') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Módulo de riego' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dren_abierto') AND attribute='MODULO';
UPDATE layers_attribute SET attribute_label = 'Subtipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_ppal') AND attribute='SUBTIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_ppal') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Módulo de riego' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_ppal') AND attribute='MODULO';
UPDATE layers_attribute SET attribute_label = 'Subtipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_lat') AND attribute='SUBTIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_lat') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Módulo de riego' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_lat') AND attribute='MODULO';
UPDATE layers_attribute SET attribute_label = 'Nmobre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'subestacion_elect') AND attribute='Nombre';
UPDATE layers_attribute SET attribute_label = 'Capacidad (MW)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'subestacion_elect') AND attribute='Cap_MW';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'subestacion_elect') AND attribute='Direccion';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'linea_elect_at') AND attribute='Name';
UPDATE layers_attribute SET attribute_label = 'Alumbrado público' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cob_alum_pub') AND attribute='alum';
UPDATE layers_attribute SET attribute_label = 'Material' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_gas_nat') AND attribute='MATERIAL';
UPDATE layers_attribute SET attribute_label = 'Longitud (pulgadas)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_gas_nat') AND attribute='DIAM_PULG';
UPDATE layers_attribute SET attribute_label = 'Longitud (km)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'red_gas_nat') AND attribute='LONG_KM';
UPDATE layers_attribute SET attribute_label = 'Superficie (ha)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cob_gas_nat') AND attribute='SUP_HA';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'usuario_ind_gas') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Colonia o fraccionamiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'usuario_resid_gas') AND attribute='COLONIAS';
UPDATE layers_attribute SET attribute_label = 'Clave de colonia o fraccionamiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'usuario_resid_gas') AND attribute='CVE_COL';
UPDATE layers_attribute SET attribute_label = 'Clave catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'unidad_rem_linea') AND attribute='CVE_CAT';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_wifi') AND attribute='NOMBRE_VIA';
UPDATE layers_attribute SET attribute_label = 'Número' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_wifi') AND attribute='NUM_EXT';
UPDATE layers_attribute SET attribute_label = 'Clave del centro' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_wifi') AND attribute='CVE_CENTRO';
UPDATE layers_attribute SET attribute_label = 'Nombre del centro' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_wifi') AND attribute='NOM_CENTRO';
UPDATE layers_attribute SET attribute_label = 'Dependencia encargada' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_wifi') AND attribute='DEPENDENCI';
UPDATE layers_attribute SET attribute_label = 'Tipo de centro' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_wifi') AND attribute='NOMENCLATU';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'antena_telecom') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cab_telefono') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Jerarquía' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'nodo_vial') AND attribute='JERARQUIA';
UPDATE layers_attribute SET attribute_label = 'Estatus' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'nodo_vial') AND attribute='ESTATUS';
UPDATE layers_attribute SET attribute_label = 'Nombre de la vialidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'evial_actual') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Acotamiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'evial_actual') AND attribute='Acotamient';
UPDATE layers_attribute SET attribute_label = 'Jerarquía' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'evial_actual') AND attribute='JERARQUIA';
UPDATE layers_attribute SET attribute_label = 'Carriles' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'evial_actual') AND attribute='CARRILES';
UPDATE layers_attribute SET attribute_label = 'Administración' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'evial_actual') AND attribute='ADMINISTRA';
UPDATE layers_attribute SET attribute_label = 'Clasificación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'evial_actual') AND attribute='CLASIFICA';
UPDATE layers_attribute SET attribute_label = 'Límite de velocidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'evial_actual') AND attribute='VELOCIDAD';
UPDATE layers_attribute SET attribute_label = 'Sección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'evial_actual') AND attribute='SECCION';
UPDATE layers_attribute SET attribute_label = 'Estado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'edo_fis_evial_ppal') AND attribute='ESTADO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'edo_fis_evial_ppal') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Jerarquía' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'edo_fis_evial_ppal') AND attribute='JERARQUIA';
UPDATE layers_attribute SET attribute_label = 'Longitud (km)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'edo_fis_evial_ppal') AND attribute='LONG_KM';
UPDATE layers_attribute SET attribute_label = 'Vialidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cob_pavimento') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Cobertura de pavimento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cob_pavimento') AND attribute='PAVIMENTO';
UPDATE layers_attribute SET attribute_label = 'Longitud (km)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cob_pavimento') AND attribute='LONG_KM';
UPDATE layers_attribute SET attribute_label = 'Longitud (km)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'par_vial') AND attribute='long_km';
UPDATE layers_attribute SET attribute_label = 'Sentido' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'par_vial') AND attribute='sentido';
UPDATE layers_attribute SET attribute_label = 'Nombre de la vialidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'par_vial') AND attribute='NOMV';
UPDATE layers_attribute SET attribute_label = 'Jerarquía' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'par_vial') AND attribute='JERQ';
UPDATE layers_attribute SET attribute_label = 'Estado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'par_vial') AND attribute='ESTADO';
UPDATE layers_attribute SET attribute_label = 'Centralizado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cruc_semaforo') AND attribute='CENTRALIZA';
UPDATE layers_attribute SET attribute_label = 'Cámara' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cruc_semaforo') AND attribute='CAMARA';
UPDATE layers_attribute SET attribute_label = 'Videodetección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cruc_semaforo') AND attribute='VIDEO_DETE';
UPDATE layers_attribute SET attribute_label = 'Jerarquía' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'alto_disco') AND attribute='JERARQUIA';
UPDATE layers_attribute SET attribute_label = 'Número de accidentes' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'accident_vial') AND attribute='ICOUNT';
UPDATE layers_attribute SET attribute_label = 'Colonia o fraccionamiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'zona_trans_rest') AND attribute='COLONIAS';
UPDATE layers_attribute SET attribute_label = 'Clave de la colonia o fraccionamiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'zona_trans_rest') AND attribute='CVE_COL';
UPDATE layers_attribute SET attribute_label = 'Superficie (ha)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'zona_trans_rest') AND attribute='SUP_HA';
UPDATE layers_attribute SET attribute_label = 'Nombre de la vialidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_ciclovia') AND attribute='NOM_VIAL';
UPDATE layers_attribute SET attribute_label = 'Longutud (km)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_ciclovia') AND attribute='LONG_KM';
UPDATE layers_attribute SET attribute_label = 'Estado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_ciclovia') AND attribute='estado';
UPDATE layers_attribute SET attribute_label = 'Etapa' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_ciclovia') AND attribute='Ciclo_Etap';
UPDATE layers_attribute SET attribute_label = 'Acotamiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_ciclovia') AND attribute='ACOTA';
UPDATE layers_attribute SET attribute_label = 'Carriles' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_ciclovia') AND attribute='CARRIL';
UPDATE layers_attribute SET attribute_label = 'Alumbrado público' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_ciclovia') AND attribute='alum';
UPDATE layers_attribute SET attribute_label = 'Estacionamiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_ciclovia') AND attribute='ESTACIO';
UPDATE layers_attribute SET attribute_label = 'Sección vial' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_ciclovia') AND attribute='SECC_VIAL';
UPDATE layers_attribute SET attribute_label = 'Cobertura de pavimentación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_ciclovia') AND attribute='PAV';
UPDATE layers_attribute SET attribute_label = 'Clave de la ruta' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_autobus') AND attribute='CVE_RUTA';
UPDATE layers_attribute SET attribute_label = 'Consesión' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_autobus') AND attribute='CONSESION';
UPDATE layers_attribute SET attribute_label = 'Alias' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_autobus') AND attribute='ALIAS';
UPDATE layers_attribute SET attribute_label = 'Parque vehicular operando' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_autobus') AND attribute='P_VEHIC_OP';
UPDATE layers_attribute SET attribute_label = 'Frecuencia (min)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_autobus') AND attribute='FREC_MIN';
UPDATE layers_attribute SET attribute_label = 'Ubicación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_autobus') AND attribute='UBICACION';
UPDATE layers_attribute SET attribute_label = 'Tiempo promedio de recorrido (min)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_autobus') AND attribute='PROM_REC_M';
UPDATE layers_attribute SET attribute_label = 'Ruta' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_autobus') AND attribute='RUTA';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cob_autobus') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Base' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'base_radiotaxi') AND attribute='BASE';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'base_radiotaxi') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'base_radiotaxi') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Sitio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_taxi') AND attribute='SITIO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_taxi') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Domicilio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_taxi') AND attribute='DOMICILIO';
UPDATE layers_attribute SET attribute_label = 'Ruta' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_taxi') AND attribute='RUTA';
UPDATE layers_attribute SET attribute_label = 'Franja' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_taxi') AND attribute='FRANJA';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_taxi') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Trayecto' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ruta_taxi') AND attribute='TRAYECTO';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cob_taxi') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Periodo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'crec_hist') AND attribute='PERIODO';
UPDATE layers_attribute SET attribute_label = 'Uso de suelo actual' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='USO_ACTUAL';
UPDATE layers_attribute SET attribute_label = 'Habitacional' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='h';
UPDATE layers_attribute SET attribute_label = 'Comercio y servicio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='cs';
UPDATE layers_attribute SET attribute_label = 'Industria' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='i';
UPDATE layers_attribute SET attribute_label = '"Mixto (habitacional, comercio y servicios)"' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='m';
UPDATE layers_attribute SET attribute_label = '"Mixto (industria, comercio y servicios)"' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='mci';
UPDATE layers_attribute SET attribute_label = 'Infraestructura' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='ia';
UPDATE layers_attribute SET attribute_label = 'Almacenamiento y servicios' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='as';
UPDATE layers_attribute SET attribute_label = 'Equipamiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='e';
UPDATE layers_attribute SET attribute_label = 'Corredor urbano' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='cu';
UPDATE layers_attribute SET attribute_label = 'Baldío urbanizado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='bu';
UPDATE layers_attribute SET attribute_label = 'Baldío no urbanizado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='bnu';
UPDATE layers_attribute SET attribute_label = 'Agrícola' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='as';
UPDATE layers_attribute SET attribute_label = 'Equipamiento (área verde)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo_actual') AND attribute='aev';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'parque_zona_ind') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'parque_zona_ind') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Superficie (ha)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'parque_zona_ind') AND attribute='SUP_HA';
UPDATE layers_attribute SET attribute_label = 'Clave catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'baldios') AND attribute='ClaveCatas';
UPDATE layers_attribute SET attribute_label = 'Superficie (m²)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'baldios') AND attribute='Superficie';
UPDATE layers_attribute SET attribute_label = 'Clave catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tenen_tierra') AND attribute='ClaveCatas';
UPDATE layers_attribute SET attribute_label = 'Tenencia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tenen_tierra') AND attribute='Prop_2019';
UPDATE layers_attribute SET attribute_label = 'Superficie (m²)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tenen_tierra') AND attribute='Shape_Area';
UPDATE layers_attribute SET attribute_label = 'Valor catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_corr_com') AND attribute='Val2019';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_corr_com') AND attribute='Nom';
UPDATE layers_attribute SET attribute_label = 'Valor catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_corr_urb') AND attribute='Val2019';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_corr_urb') AND attribute='Nom';
UPDATE layers_attribute SET attribute_label = 'Valor catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_hab') AND attribute='Val2019';
UPDATE layers_attribute SET attribute_label = 'Clave de la colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_hab') AND attribute='Colonia';
UPDATE layers_attribute SET attribute_label = 'Nombre de la colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_hab') AND attribute='Desc_';
UPDATE layers_attribute SET attribute_label = 'Valor catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_industria') AND attribute='Val2019';
UPDATE layers_attribute SET attribute_label = 'Clave de la colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_industria') AND attribute='Colonia';
UPDATE layers_attribute SET attribute_label = 'Nombre de la colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_industria') AND attribute='Desc_';
UPDATE layers_attribute SET attribute_label = 'Valor catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_plza_ctro_com') AND attribute='Val2019';
UPDATE layers_attribute SET attribute_label = 'Clave de la colonia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_plza_ctro_com') AND attribute='Colonia';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_plza_ctro_com') AND attribute='Nom';
UPDATE layers_attribute SET attribute_label = 'Valor catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_reserva') AND attribute='Val2019';
UPDATE layers_attribute SET attribute_label = 'Valor catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'valor_cat_rustico') AND attribute='Val2019';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ctro_com_ppal') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Nombre del establecimiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'oferta_tur_ppal') AND attribute='nom_estab';
UPDATE layers_attribute SET attribute_label = 'Colonia o fraccionamiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'oferta_tur_ppal') AND attribute='nomb_asent';
UPDATE layers_attribute SET attribute_label = 'Nombre del corredor (vialidad)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'corr_turistico') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Colonia o fraccionamiento' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'zona_turistica') AND attribute='COLONIA';
UPDATE layers_attribute SET attribute_label = 'Periodo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'crec_hist_viv') AND attribute='PERIODO';
UPDATE layers_attribute SET attribute_label = 'Viviendas totales' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2010') AND attribute='VIV_TOT';
UPDATE layers_attribute SET attribute_label = 'Viviendas particulares deshabitadas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2011') AND attribute='VIV_PARDES';
UPDATE layers_attribute SET attribute_label = 'Viviendas habitadas con piso diferente de tierra' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2012') AND attribute='VPH_PISODT';
UPDATE layers_attribute SET attribute_label = 'Viviendas habitadas con servicios básicos' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agebs_2013') AND attribute='VPH_C_SERV';
UPDATE layers_attribute SET attribute_label = 'Tipo de vivienda' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tipo_viv') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Superficie (ha)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tipo_viv') AND attribute='SUP_HA';
UPDATE layers_attribute SET attribute_label = 'Plazo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'reservas_hab') AND attribute='PLAZO';
UPDATE layers_attribute SET attribute_label = 'Superficie (ha)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'reservas_hab') AND attribute='Hectares';
UPDATE layers_attribute SET attribute_label = 'Sistema' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sist_topoformas') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Provincia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'provincia_fisio') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Subprovincia' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'subprov_fisio') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Elevación (msnm)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'mde_mpio_mxl') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'zona_inund') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Tipo de roca' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'geologia') AND attribute='TIPO_LEY';
UPDATE layers_attribute SET attribute_label = 'Tipo de suelo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'edafologia') AND attribute='NOM_SUE1';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_riego') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Subtipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_riego') AND attribute='SUBTIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_riego') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Cargo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_riego') AND attribute='CARGO';
UPDATE layers_attribute SET attribute_label = 'Módulo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canal_riego') AND attribute='MODULO';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cauce_rio_colorado') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Región' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cuenca_hidro') AND attribute='REGION';
UPDATE layers_attribute SET attribute_label = 'Cuenca' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cuenca_hidro') AND attribute='CUENCA';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'cuerpo_agua_inter') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dren_134') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dren_ppal') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Módulo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dren_ppal') AND attribute='MODULO';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dren_ramal_subramal') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dren_ramal_subramal') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Módulo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dren_ramal_subramal') AND attribute='MODULO';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dv_dren134') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Área (m²)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'modulo_riego') AND attribute='DR014_AREA';
UPDATE layers_attribute SET attribute_label = 'Número de módulo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'modulo_riego') AND attribute='DR014MODU';
UPDATE layers_attribute SET attribute_label = 'Usuarios' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'modulo_riego') AND attribute='TOTAL_USER';
UPDATE layers_attribute SET attribute_label = 'Volumen anual (m³)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'modulo_riego') AND attribute='TOTAL_VOL';
UPDATE layers_attribute SET attribute_label = 'Pozos' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'modulo_riego') AND attribute='TOTAL_POZS';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'arroyo_ppal') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'arroyo_ppal') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Nombre de la región' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'acuiferos') AND attribute='NOM_REGION';
UPDATE layers_attribute SET attribute_label = 'Clave del acuífero' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'acuiferos') AND attribute='CLV_ACUI';
UPDATE layers_attribute SET attribute_label = 'Nombre del acuífero' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'acuiferos') AND attribute='NOM_ACUI';
UPDATE layers_attribute SET attribute_label = 'Superficie (km²)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'acuiferos') AND attribute='AREA_KM2';
UPDATE layers_attribute SET attribute_label = 'Disponibilidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'acuiferos') AND attribute='DESC_DISPO';
UPDATE layers_attribute SET attribute_label = 'Sobreexplotación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'acuiferos') AND attribute='SOBREEXP';
UPDATE layers_attribute SET attribute_label = 'Fecha de publicación (DOF)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'acuiferos') AND attribute='FECHA_DOFD';
UPDATE layers_attribute SET attribute_label = 'Unidad geohidrológica' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'unidad_geohidro') AND attribute='UNID_GEOHI';
UPDATE layers_attribute SET attribute_label = 'Superficie (m²)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'unidad_geohidro') AND attribute='AREA';
UPDATE layers_attribute SET attribute_label = 'Tipo de clima' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tipo_clima') AND attribute='CLIMA_TIPO';
UPDATE layers_attribute SET attribute_label = 'Clima' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tipo_clima') AND attribute='DES_TEM';
UPDATE layers_attribute SET attribute_label = 'Precipitación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tipo_clima') AND attribute='DEC_PREC';
UPDATE layers_attribute SET attribute_label = 'Temperatura media' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'temp_med_anual') AND attribute='CLAVESTEM';
UPDATE layers_attribute SET attribute_label = 'Temperatura máxima absoluta (°C)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'temp_max_abs') AND attribute='TA_RANGO';
UPDATE layers_attribute SET attribute_label = 'Temperatura máxima promedio (°C)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'temp_max_prom') AND attribute='TA_RANGO';
UPDATE layers_attribute SET attribute_label = 'Temperatura mínima absoluta (°C)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'temp_min_abs') AND attribute='TA_RANGO';
UPDATE layers_attribute SET attribute_label = 'Temperatura mínima promedio (°C)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'temp_min_prom') AND attribute='TA_RANGO';
UPDATE layers_attribute SET attribute_label = 'Temperatura mínima extrema (°C)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'temp_min_extrema') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Tipología' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo') AND attribute='CVE_G';
UPDATE layers_attribute SET attribute_label = 'Agrícola' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo') AND attribute='RAP';
UPDATE layers_attribute SET attribute_label = 'Acuícola' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo') AND attribute='ACUI';
UPDATE layers_attribute SET attribute_label = 'Pastizal cultivado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo') AND attribute='PC';
UPDATE layers_attribute SET attribute_label = '"Información ecológica, florística y fisionómica"' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo') AND attribute='IEFF';
UPDATE layers_attribute SET attribute_label = 'Cuerpo de agua' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'uso_suelo') AND attribute='H2O';
UPDATE layers_attribute SET attribute_label = 'Tipología' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'vegetacion') AND attribute='descripcio';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_nat_prot') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Categoría de decreto' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_nat_prot') AND attribute='CAT_DECRET';
UPDATE layers_attribute SET attribute_label = 'Categoría de manejo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_nat_prot') AND attribute='CAT_MANEJO';
UPDATE layers_attribute SET attribute_label = 'Estados' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_nat_prot') AND attribute='ESTADOS';
UPDATE layers_attribute SET attribute_label = 'Municipios' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_nat_prot') AND attribute='MUNICIPIOS';
UPDATE layers_attribute SET attribute_label = 'Región' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_nat_prot') AND attribute='REGION';
UPDATE layers_attribute SET attribute_label = 'Superficie (m²)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_nat_prot') AND attribute='SUPERFICIE';
UPDATE layers_attribute SET attribute_label = 'Última publicación (DOF)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_nat_prot') AND attribute='ULT_DOF';
UPDATE layers_attribute SET attribute_label = 'Ubicación del sitio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_ramsar') AND attribute='RAMSAR';
UPDATE layers_attribute SET attribute_label = 'Fecha de ingreso' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_ramsar') AND attribute='FECHA_INGR';
UPDATE layers_attribute SET attribute_label = 'Municipios' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_ramsar') AND attribute='MUNICIPIOS';
UPDATE layers_attribute SET attribute_label = 'Número de registro RAMSAR' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_ramsar') AND attribute='NUM_RAMSAR';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'area_conserv') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Región' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='DESCRIP';
UPDATE layers_attribute SET attribute_label = 'Superficie (ha)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='HECTAREA';
UPDATE layers_attribute SET attribute_label = 'Suelo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='SUELO';
UPDATE layers_attribute SET attribute_label = 'Vegetación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='VEGETACION';
UPDATE layers_attribute SET attribute_label = 'Uso del suelo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='USO';
UPDATE layers_attribute SET attribute_label = 'Drenaje' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='DRENAJE';
UPDATE layers_attribute SET attribute_label = 'Cuerpo de agua' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='CUERPO_H2O';
UPDATE layers_attribute SET attribute_label = 'Corriente' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='CORRIENTE';
UPDATE layers_attribute SET attribute_label = 'Estado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='ESTADO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='NOMHUMEDAL';
UPDATE layers_attribute SET attribute_label = 'Región hidrográfica' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='REGION_HID';
UPDATE layers_attribute SET attribute_label = 'Cuenca' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'humedal') AND attribute='NOM_CUENCA';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'asist_social') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'asist_social') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Localidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'asist_social') AND attribute='LOC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bomberos') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bomberos') AND attribute='DIRECCION';
UPDATE layers_attribute SET attribute_label = 'Localidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bomberos') AND attribute='LOCALIDAD';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'est_serv') AND attribute='RAZON_SOC';
UPDATE layers_attribute SET attribute_label = 'Dirección' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'est_serv') AND attribute='UBICACION';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'est_serv') AND attribute='SUBTIPO';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'hospital') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Tipo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'hospital') AND attribute='TIPO';
UPDATE layers_attribute SET attribute_label = 'Institución' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'hospital') AND attribute='INT';
UPDATE layers_attribute SET attribute_label = 'Modalidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'preescolar1') AND attribute='MODEL';
UPDATE layers_attribute SET attribute_label = 'Localidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'preescolar_1') AND attribute='LOC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'preescolar_1') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'primaria_1') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Modalidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'primaria_1') AND attribute='MODAL';
UPDATE layers_attribute SET attribute_label = 'Localidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'primaria_1') AND attribute='LOC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'secundaria_1') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Modalidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'secundaria_1') AND attribute='MODAL';
UPDATE layers_attribute SET attribute_label = 'Localidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'secundaria_1') AND attribute='LOC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_abierto') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Localidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_abierto') AND attribute='LOC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_gral') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Modalidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_gral') AND attribute='MODAL';
UPDATE layers_attribute SET attribute_label = 'Localidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_gral') AND attribute='LOC';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_tec_prof') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Localidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'bach_tec_prof') AND attribute='LOC';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'reserv_cdmxl') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'volcan') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'fallas_gral') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'falla_Suarez2008') AND attribute='Name';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'estruct_dan_falla_cerroprieto') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sitio_subsidencia') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agrieta_fi79_80') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ctro_disper') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'fallas_artSuarez') AND attribute='Layer';
UPDATE layers_attribute SET attribute_label = 'Intensidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sismo_3_3_9') AND attribute='Name';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sismo1892_7_2') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sismo1934_6_5') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Intensidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sismo_hist_m_7') AND attribute='Name';
UPDATE layers_attribute SET attribute_label = 'Año' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sismo_hist_m_7') AND attribute='DATE';
UPDATE layers_attribute SET attribute_label = 'Intensidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sismo_6_6_9') AND attribute='Name';
UPDATE layers_attribute SET attribute_label = 'Año' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sismo_6_6_9') AND attribute='DATE';
UPDATE layers_attribute SET attribute_label = 'Intensidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sismo_5_5_9') AND attribute='Name';
UPDATE layers_attribute SET attribute_label = 'Intensidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sismo_4_4_9') AND attribute='Name';
UPDATE layers_attribute SET attribute_label = 'Área de recepción' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tsunamis') AND attribute='AREA_RECEP';
UPDATE layers_attribute SET attribute_label = 'Rangos (°)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'pendientes_mpio_mxl') AND attribute='VALUE';
UPDATE layers_attribute SET attribute_label = 'Grado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'suscep_ladera') AND attribute='Value';
UPDATE layers_attribute SET attribute_label = 'Grado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'sus_inest_laderas') AND attribute='Value';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'volcan_arena_centro1940') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'volcan_arena_imperial1979') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'volcan_arena_victoria1980') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'zona_licue_agrieta') AND attribute='';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'canada') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Ubicación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agrietamiento') AND attribute='Field1';
UPDATE layers_attribute SET attribute_label = 'Elemento dañado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'agrietamiento') AND attribute='Field3';
UPDATE layers_attribute SET attribute_label = 'Altura de la estación (m)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'est_clima') AND attribute='ALT_m';
UPDATE layers_attribute SET attribute_label = 'Número de estación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'est_clima') AND attribute='NO_EST';
UPDATE layers_attribute SET attribute_label = 'Nombre de la estación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'est_clima') AND attribute='NOM_EST';
UPDATE layers_attribute SET attribute_label = '' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'prob_sequia') AND attribute='';
UPDATE layers_attribute SET attribute_label = 'Nombre de municipio' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ind_heladas') AND attribute='NOM_MUN';
UPDATE layers_attribute SET attribute_label = 'Población' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ind_heladas') AND attribute='POB2010';
UPDATE layers_attribute SET attribute_label = 'Estado' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ind_heladas') AND attribute='ESTADO_1';
UPDATE layers_attribute SET attribute_label = 'Grado (índice)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ind_heladas') AND attribute='PELIGRO_PO';
UPDATE layers_attribute SET attribute_label = 'Intensidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'isoterma_int') AND attribute='Intensidad';
UPDATE layers_attribute SET attribute_label = 'Temperatura (°C)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'isoterma_int') AND attribute='Contour';
UPDATE layers_attribute SET attribute_label = 'Temperatura (°C)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'temp_min_estrema') AND attribute='Value';
UPDATE layers_attribute SET attribute_label = 'Días con granizo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'dias_granizo') AND attribute='DIAS_GRANI';
UPDATE layers_attribute SET attribute_label = 'Cantidad de granziadas' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'int_granizo') AND attribute='OBSERV';
UPDATE layers_attribute SET attribute_label = 'Intensidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'int_granizo') AND attribute='INF_COMPL';
UPDATE layers_attribute SET attribute_label = 'Rango de elevación (msnm)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'prob_alt_nevada') AND attribute='RANGO';
UPDATE layers_attribute SET attribute_label = 'Probabilidad de nevada' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'prob_alt_nevada') AND attribute='PROBABILID';
UPDATE layers_attribute SET attribute_label = 'Nombre' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tray_ciclon') AND attribute='NOMBRE';
UPDATE layers_attribute SET attribute_label = 'Clasificación' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tray_ciclon') AND attribute='CLASIF';
UPDATE layers_attribute SET attribute_label = 'Fecha' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'tray_ciclon') AND attribute='FECHA';
UPDATE layers_attribute SET attribute_label = 'Cantidad de impactos' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'ciclon_costa') AND attribute='Name';
UPDATE layers_attribute SET attribute_label = 'Nombre de la localidad' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'afect_loc_ciclon') AND attribute='Name';
UPDATE layers_attribute SET attribute_label = 'Número de ciclones impactados' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'afect_loc_ciclon') AND attribute='PopupInfo';
UPDATE layers_attribute SET attribute_label = 'Clave catastral' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'pred_afect_dren134') AND attribute='CLAVECATAS';
UPDATE layers_attribute SET attribute_label = 'Superficie (m²)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'pred_afect_dren134') AND attribute='SUPERFICIE';
UPDATE layers_attribute SET attribute_label = 'Giro' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'pred_afect_dren134') AND attribute='GIRO';
UPDATE layers_attribute SET attribute_label = 'Nivel de riesgo' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'pred_afect_dren134') AND attribute='RIESGO_1';
UPDATE layers_attribute SET attribute_label = 'Profundidad (m)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'inund_1982') AND attribute='Value';
UPDATE layers_attribute SET attribute_label = 'Profundidad (m)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'inund_1983') AND attribute='Value';
UPDATE layers_attribute SET attribute_label = 'Profundidad (m)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'inund_1995') AND attribute='Value';
UPDATE layers_attribute SET attribute_label = 'Profundidad (m)' WHERE layer_id = (SELECT resourcebase_ptr_id FROM layers_layer WHERE name = 'inund_2008') AND attribute='Value';
